### ISSUE TITLE
Question about potentially undocumented API endpoints

### ISSUE THREAD

**Issue by d4rky-pl** [RecastAI/Webchat#11]
I've noticed that this Webchat uses [endpoint that I could not find in API documentation](https://github.com/RecastAI/Webchat/blob/master/src/actions/messages.js#L19). Are they undocumented or was I looking in the wrong place and if it's the latter, what would be the place to look for them so I can add the link to README and send a PR? :)

**Comment by dbousque** [comment]
Hi @d4rky-pl, thanks for your interest. Yes this endpoint is intentionally not documented as is, let me know if I can help you with it :)

**Comment by d4rky-pl** [comment]
I think we managed to reverse engineer this ourselves ;) Question though, why isn't it documented?

**Comment by dbousque** [comment]
Hi @d4rky-pl, well done ! We want to remain free to make breaking changes to this part of the API, we don't do it often, and when we do the changes are small, but we don't want to commit to making 0 changes to this part of the API, so we don't document it :)
