### ISSUE TITLE
Using Webchat Channel: message type "list" is not displayed 

### ISSUE THREAD

**Issue by abcl0653** [RecastAI/Webchat#12]
In the bot i use list of response message, it looks good in recast.ai Test/CHAT WITH YOUR BOT.
But when i tried to use WebChat channel, everything is the same as in CHAT WITH YOUR BOT except:
The bot response with empty message when it suppose to be a list.

The button and text message is fine. only the list type message is not displayed.

I trace the network and it looks the list content is returned, but it is just not displayed.

I tested in Chrome and Safari.

Is it a known issue? or do i did something wrong?

**Comment by jhoudan** [comment]
There was an issue introduced by a security fix, preventing list and cards with empty imageUrl field to be displayed. It has been fixed today, can you confirm that it works as intended on your side as well?

**Comment by abcl0653** [comment]
> There was an issue introduced by a security fix, preventing list and cards with empty imageUrl field to be displayed. It has been fixed today, can you confirm that it works as intended on your side as well?

Yes, Jhoudan, it works now. Thanks a lot!

**Comment by drivenrajat** [comment]
List is not showing as of today.
