### ISSUE TITLE
How to create webchat iframe window?

### ISSUE THREAD

**Issue by tomuskey** [RecastAI/Webchat#28]
for example snatchbot.me has the dedicated link for the webchat which I could embed to my site wherever I want

For example 
`<iframe src="https://snatchbot.me/webchat/?botID=xxxxxx&appID=IZxx0Q4kcjNhJWtW61ExxO06b" width="100%" height="100%" frameborder="0" scrolling="no"></iframe>`

Can I make the same with recast.ai webchat? How?

**Comment by dbousque** [comment]
Hi @tomuskey, you can do something similar with our webchat indeed, take a look here : https://recast.ai/docs/concepts/webchat
