### ISSUE TITLE
Custom Webchat widget

### ISSUE THREAD

**Issue by UsulPro** [RecastAI/Webchat#4]
Hi, guys!

At my company, we are looking for a chatbot service for a website with a strict condition to have an entire own appearance of a web widget. So looks like this repo really fits for us as we want to create own bot client based on this project and still use https://recast.ai as a chatbot service.  But could you please confirm that we can fork this repo, modify it as we need and connect to our user Webchat channel without any gotchas? 

Thanks in advance!

**Comment by dbousque** [comment]
Hi @UsulPro :) Yes absolutely. For the legal part : you can use the code as you wish, including distributing/selling it as is, or with modifications (more details : https://github.com/RecastAI/Webchat/blob/master/LICENSE). For the technical part : You can create a 'Webchat' channel in the 'Connect' tab of your bot, and then use your custom webchat on your website. As long as the behavior regarding the backend API doesn't change, things will work smoothly.

Let me know if I can help you further :)
